// packages/recruiting/src/routes/login.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { page } from '$app/state';
  import { NuvolarisClient } from '$lib/api';
  import { API_BASE_URL } from '$lib/constants';
  import { toast } from 'sonner';

  const client = new NuvolarisClient(API_BASE_URL);
  let email = '';
  let password = '';
  let loading = false;

  async function handleSubmit(e: Event) {
    e.preventDefault();
    loading = true;
    
    try {
      const response = await client.login(email, password);
      
      if (response.token) {
        document.cookie = `token=${response.token}; path=/; max-age=604800`;
        toast.success('Login successful!');
        goto('/');
      }
    } catch (error: any) {
      toast.error(error.message || 'Login failed');
    } finally {
      loading = false;
    }
  }
</script>

<div class="flex min-h-screen items-center justify-center bg-gradient-to-br from-background via-background to-muted">
  <div class="w-full max-w-md px-6">
    <div class="flex flex-col items-center space-y-8">
      <div class="animate-in fade-in zoom-in duration-500">
        <img src="/trustable.png" alt="Trustable Logo" class="h-24 w-auto" />
      </div>

      <div class="w-full animate-in fade-in slide-in-from-bottom-4 duration-700 delay-150">
        <div class="rounded-2xl border bg-card p-8 shadow-elegant">
          <h1 class="mb-2 text-2xl font-bold text-foreground">Welcome Back</h1>
          <p class="mb-6 text-muted-foreground">Sign in to your account</p>

          <form onsubmit={handleSubmit} class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-foreground">Email</label>
              <input
                type="email"
                bind:value={email}
                required
                class="mt-1 block w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                placeholder="Enter your email"
              />
            </div>

            <div>
              <label class="block text-sm font-medium text-foreground">Password</label>
              <input
                type="password"
                bind:value={password}
                required
                class="mt-1 block w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                placeholder="Enter your password"
              />
            </div>

            <button
              type="submit"
              disabled={loading}
              class="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2 w-full"
            >
              {#if loading}
                <span class="animate-spin">Loading...</span>
              {:else}
                Sign In
              {/if}
            </button>
          </form>

          <p class="mt-4 text-center text-sm text-muted-foreground">
            Don't have an account? 
            <a href="/register" class="underline underline-offset-4 hover:text-primary">Sign up</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

// src/pages/Login.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { apiPost } from '@/lib/api';

interface User {
  id: number;
  name?: string;
  email: string;
  role: string;
}

interface LoginResponse {
  success: boolean;
  token?: string;
  user?: User;
  error?: string;
}

const Login = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const response: LoginResponse = await apiPost('/web/v1/auth/login', { email, password });
      
      if (response.success && response.token) {
        localStorage.setItem('token', response.token);
        if (response.user?.role === 'recruiter') {
          navigate('/recruiter/dashboard');
        } else {
          navigate('/candidate/dashboard');
        }
      }
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Login failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-background via-background to-muted px-4">
      <div className="w-full max-w-md">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold">RecruitMe</h1>
          <p className="text-muted-foreground mt-2">Candidate Assessment Platform</p>
        </div>
        
        <div className="rounded-2xl border bg-card p-8 shadow-elegant">
          <h2 className="text-2xl font-bold mb-6">Login</h2>
          
          {error && (
            <div className="mb-4 rounded-md bg-destructive/15 p-3 text-sm text-destructive">
              {error}
            </div>
          )}
          
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
                placeholder="Enter your email"
              />
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input
                id="password"
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
                placeholder="Enter your password"
              />
            </div>
            
            <Button type="submit" className="w-full" disabled={loading}>
              {loading ? 'Logging in...' : 'Login'}
            </Button>
          </form>
          
          <p className="mt-4 text-center text-sm text-muted-foreground">
            Don't have an account?{' '}
            <button
              onClick={() => navigate('/register')}
              className="text-primary underline underline-offset-4 hover:text-primary/80"
            >
              Register
            </button>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Login;
